import test from 'node:test';
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { estimateQuote } from './estimate.js';
import { resolveVisibleFields } from './visibility.js';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const FIXTURES_DIR = path.join(HERE, '__fixtures__');

// Fixtures are generated by the merchi_api fixture generator from the real
// specialised-order-estimate endpoint (the same set vendored into
// merchi_sdk_ts), so both SDKs are validated against one server source.
function loadFixtures() {
  if (!fs.existsSync(FIXTURES_DIR)) return [];
  return fs
    .readdirSync(FIXTURES_DIR)
    .filter((f) => f.endsWith('.json'))
    .map((f) => JSON.parse(fs.readFileSync(path.join(FIXTURES_DIR, f), 'utf-8')));
}

function closeTo(actual, expected, dp) {
  const tolerance = 0.5 * Math.pow(10, -dp);
  assert.ok(
    Math.abs(actual - expected) < tolerance,
    `expected ${actual} to be within ${tolerance} of ${expected}`
  );
}

const fixtures = loadFixtures();

test('pricing fixtures exist', () => {
  assert.ok(fixtures.length > 0, 'no fixtures found');
});

for (const fixture of fixtures) {
  test(`golden parity: ${fixture.name} - estimateQuote matches server`, () => {
    const result = estimateQuote(fixture.bundle, fixture.selections);
    closeTo(result.cost, fixture.expected.cost, 2);
    closeTo(result.costPerUnit, fixture.expected.costPerUnit, 3);
    closeTo(result.taxAmount, fixture.expected.taxAmount, 2);
    closeTo(result.totalCost, fixture.expected.totalCost, 2);
    assert.equal(result.groupCosts.length, fixture.expected.groupCosts.length);
    result.groupCosts.forEach((c, i) => closeTo(c, fixture.expected.groupCosts[i], 2));
  });

  test(`golden parity: ${fixture.name} - resolveVisibleFields matches server`, () => {
    const visible = [...resolveVisibleFields(fixture.bundle, fixture.selections)].sort(
      (a, b) => a - b
    );
    assert.deepEqual(visible, fixture.expected.visibleFieldIds);
  });
}
